/* ═══════════ HBC v18 — BEÉPÍTETT MAGYAR SZÉNHIDRÁTTÁBLÁZAT (6.1) ═══════════
   Offline étellista a magyar konyha gyakori ételeivel. Tételenként tipikus
   adag és szénhidráttartalom (g). A CH-értékek átlagos, kerekített értékek
   hazai tápanyagtáblázatok alapján — a pontos érték terméktől függően eltérhet!
   A lista a Beállításokban kapcsolható ki-be (alapból BE). */

window.CH_TABLE = [
 /* ── PÉKÁRU, KENYÉRFÉLÉK ── */
 { cat: 'Pékáru', name: 'Fehér kenyér', carbs: 15, unit: '1 vékony szelet (30 g)' },
 { cat: 'Pékáru', name: 'Félbarna kenyér', carbs: 14, unit: '1 vékony szelet (30 g)' },
 { cat: 'Pékáru', name: 'Teljes kiőrlésű kenyér', carbs: 12, unit: '1 vékony szelet (30 g)' },
 { cat: 'Pékáru', name: 'Rozskenyér', carbs: 13, unit: '1 vékony szelet (30 g)' },
 { cat: 'Pékáru', name: 'Kovászos kenyér', carbs: 15, unit: '1 vékony szelet (30 g)' },
 { cat: 'Pékáru', name: 'Zsemle', carbs: 25, unit: '1 db (50 g)' },
 { cat: 'Pékáru', name: 'Kifli', carbs: 22, unit: '1 db (44 g)' },
 { cat: 'Pékáru', name: 'Császárzsemle', carbs: 27, unit: '1 db (55 g)' },
 { cat: 'Pékáru', name: 'Magvas zsemle', carbs: 22, unit: '1 db (55 g)' },
 { cat: 'Pékáru', name: 'Briós', carbs: 28, unit: '1 db (60 g)' },
 { cat: 'Pékáru', name: 'Kakaós csiga', carbs: 42, unit: '1 db (90 g)' },
 { cat: 'Pékáru', name: 'Túrós batyu', carbs: 35, unit: '1 db (90 g)' },
 { cat: 'Pékáru', name: 'Croissant (vajas)', carbs: 25, unit: '1 db (55 g)' },
 { cat: 'Pékáru', name: 'Pogácsa (tepertős)', carbs: 15, unit: '1 db (40 g)' },
 { cat: 'Pékáru', name: 'Lángos (sima)', carbs: 45, unit: '1 db (150 g)' },
 { cat: 'Pékáru', name: 'Toast kenyér', carbs: 12, unit: '1 szelet (25 g)' },
 { cat: 'Pékáru', name: 'Bagett', carbs: 28, unit: '10 cm-es darab (50 g)' },
 { cat: 'Pékáru', name: 'Tortilla lap', carbs: 30, unit: '1 db (60 g)' },
 { cat: 'Pékáru', name: 'Knäckebrot', carbs: 7, unit: '1 szelet (10 g)' },
 { cat: 'Pékáru', name: 'Abonett', carbs: 4, unit: '1 szelet (6 g)' },
 { cat: 'Pékáru', name: 'Korpovit keksz', carbs: 5, unit: '1 db (8 g)' },
 { cat: 'Pékáru', name: 'Graham kenyér', carbs: 13, unit: '1 vékony szelet (30 g)' },
 { cat: 'Pékáru', name: 'Kalács (fonott)', carbs: 26, unit: '1 szelet (50 g)' },
 { cat: 'Pékáru', name: 'Bejgli (diós/mákos)', carbs: 28, unit: '1 szelet (50 g)' },

 /* ── KÖRETEK, GABONÁK, TÉSZTÁK ── */
 { cat: 'Köret', name: 'Főtt rizs', carbs: 40, unit: '1 adag (140 g főtt)' },
 { cat: 'Köret', name: 'Barna rizs (főtt)', carbs: 36, unit: '1 adag (140 g főtt)' },
 { cat: 'Köret', name: 'Bulgur (főtt)', carbs: 26, unit: '1 adag (140 g főtt)' },
 { cat: 'Köret', name: 'Kuszkusz (főtt)', carbs: 32, unit: '1 adag (140 g főtt)' },
 { cat: 'Köret', name: 'Quinoa (főtt)', carbs: 30, unit: '1 adag (140 g főtt)' },
 { cat: 'Köret', name: 'Főtt burgonya', carbs: 30, unit: '2 közepes db (150 g)' },
 { cat: 'Köret', name: 'Burgonyapüré', carbs: 30, unit: '1 adag (200 g)' },
 { cat: 'Köret', name: 'Sült burgonya (hasáb)', carbs: 45, unit: '1 adag (150 g)' },
 { cat: 'Köret', name: 'Petrezselymes burgonya', carbs: 32, unit: '1 adag (160 g)' },
 { cat: 'Köret', name: 'Édesburgonya (sült)', carbs: 30, unit: '1 adag (150 g)' },
 { cat: 'Köret', name: 'Főtt tészta (durum)', carbs: 45, unit: '1 adag (150 g főtt)' },
 { cat: 'Köret', name: 'Spagetti (főtt)', carbs: 45, unit: '1 adag (150 g főtt)' },
 { cat: 'Köret', name: 'Penne (főtt)', carbs: 45, unit: '1 adag (150 g főtt)' },
 { cat: 'Köret', name: 'Tarhonya (főtt)', carbs: 40, unit: '1 adag (150 g főtt)' },
 { cat: 'Köret', name: 'Nokedli / galuska', carbs: 42, unit: '1 adag (150 g)' },
 { cat: 'Köret', name: 'Zsemlegombóc', carbs: 30, unit: '1 db (80 g)' },
 { cat: 'Köret', name: 'Krokett', carbs: 24, unit: '4 db (80 g)' },
 { cat: 'Köret', name: 'Rizi-bizi', carbs: 42, unit: '1 adag (150 g)' },
 { cat: 'Köret', name: 'Kukorica (főtt/konzerv)', carbs: 20, unit: '1 adag (100 g)' },
 { cat: 'Köret', name: 'Zabpehely (nyers)', carbs: 30, unit: '5 evőkanál (50 g)' },
 { cat: 'Köret', name: 'Müzli (natúr)', carbs: 32, unit: '1 adag (50 g)' },
 { cat: 'Köret', name: 'Kukoricapehely (corn flakes)', carbs: 25, unit: '1 adag (30 g)' },
 { cat: 'Köret', name: 'Puffasztott rizs', carbs: 8, unit: '1 szelet (10 g)' },
 { cat: 'Köret', name: 'Lencse (főtt)', carbs: 24, unit: '1 adag (120 g)' },
 { cat: 'Köret', name: 'Sárgaborsó-főzelék', carbs: 30, unit: '1 adag (250 g)' },
 { cat: 'Köret', name: 'Vörösbab (konzerv)', carbs: 18, unit: '1 adag (120 g)' },
 { cat: 'Köret', name: 'Csicseriborsó (főtt)', carbs: 22, unit: '1 adag (120 g)' },

 /* ── LEVESEK ── */
 { cat: 'Leves', name: 'Húsleves (tésztával)', carbs: 12, unit: '1 tányér (300 ml)' },
 { cat: 'Leves', name: 'Húsleves (tészta nélkül)', carbs: 3, unit: '1 tányér (300 ml)' },
 { cat: 'Leves', name: 'Paradicsomleves (betéttel)', carbs: 25, unit: '1 tányér (300 ml)' },
 { cat: 'Leves', name: 'Gulyásleves', carbs: 18, unit: '1 tányér (400 ml)' },
 { cat: 'Leves', name: 'Bableves (Jókai)', carbs: 30, unit: '1 tányér (400 ml)' },
 { cat: 'Leves', name: 'Lencseleves', carbs: 25, unit: '1 tányér (300 ml)' },
 { cat: 'Leves', name: 'Zöldségleves', carbs: 15, unit: '1 tányér (300 ml)' },
 { cat: 'Leves', name: 'Gyümölcsleves (hideg)', carbs: 30, unit: '1 tányér (300 ml)' },
 { cat: 'Leves', name: 'Krumplileves', carbs: 22, unit: '1 tányér (300 ml)' },
 { cat: 'Leves', name: 'Karfiolleves', carbs: 10, unit: '1 tányér (300 ml)' },
 { cat: 'Leves', name: 'Gombaleves', carbs: 8, unit: '1 tányér (300 ml)' },
 { cat: 'Leves', name: 'Halászlé', carbs: 6, unit: '1 tányér (400 ml)' },

 /* ── FŐÉTELEK, MAGYAROS ÉTELEK ── */
 { cat: 'Főétel', name: 'Rántott hús (panír)', carbs: 12, unit: '1 szelet (120 g)' },
 { cat: 'Főétel', name: 'Rántott sajt', carbs: 18, unit: '2 szelet (120 g)' },
 { cat: 'Főétel', name: 'Pörkölt (sertés)', carbs: 6, unit: '1 adag (200 g)' },
 { cat: 'Főétel', name: 'Csirkepaprikás', carbs: 8, unit: '1 adag (250 g)' },
 { cat: 'Főétel', name: 'Töltött káposzta', carbs: 25, unit: '2 db töltelék + káposzta (350 g)' },
 { cat: 'Főétel', name: 'Töltött paprika', carbs: 28, unit: '2 db + szósz (350 g)' },
 { cat: 'Főétel', name: 'Rakott krumpli', carbs: 45, unit: '1 adag (350 g)' },
 { cat: 'Főétel', name: 'Rakott kelkáposzta', carbs: 30, unit: '1 adag (350 g)' },
 { cat: 'Főétel', name: 'Lecsó (kolbásszal)', carbs: 15, unit: '1 adag (300 g)' },
 { cat: 'Főétel', name: 'Paprikás krumpli', carbs: 40, unit: '1 adag (350 g)' },
 { cat: 'Főétel', name: 'Főzelék (zöldbab)', carbs: 20, unit: '1 adag (250 g)' },
 { cat: 'Főétel', name: 'Főzelék (tök)', carbs: 18, unit: '1 adag (250 g)' },
 { cat: 'Főétel', name: 'Főzelék (spenót)', carbs: 15, unit: '1 adag (250 g)' },
 { cat: 'Főétel', name: 'Főzelék (krumpli)', carbs: 35, unit: '1 adag (250 g)' },
 { cat: 'Főétel', name: 'Bolognai spagetti', carbs: 55, unit: '1 adag (350 g)' },
 { cat: 'Főétel', name: 'Carbonara tészta', carbs: 50, unit: '1 adag (350 g)' },
 { cat: 'Főétel', name: 'Lasagne', carbs: 40, unit: '1 adag (300 g)' },
 { cat: 'Főétel', name: 'Pizza (Margherita)', carbs: 90, unit: '1 db 32 cm (450 g)' },
 { cat: 'Főétel', name: 'Pizza (1 szelet)', carbs: 12, unit: '1/8 szelet' },
 { cat: 'Főétel', name: 'Hamburger (átlagos)', carbs: 35, unit: '1 db' },
 { cat: 'Főétel', name: 'Gyros pitában', carbs: 45, unit: '1 db' },
 { cat: 'Főétel', name: 'Gyros tál (hasábbal)', carbs: 50, unit: '1 adag' },
 { cat: 'Főétel', name: 'Sült hal (natúr)', carbs: 1, unit: '1 szelet (150 g)' },
 { cat: 'Főétel', name: 'Sült csirkecomb (natúr)', carbs: 0, unit: '1 db (150 g)' },
 { cat: 'Főétel', name: 'Tükörtojás / rántotta', carbs: 1, unit: '2 tojásból' },
 { cat: 'Főétel', name: 'Virsli', carbs: 3, unit: '2 pár (100 g)' },
 { cat: 'Főétel', name: 'Hekk (rántott)', carbs: 10, unit: '1 adag (200 g)' },

 /* ── TÉSZTAÉTELEK, ÉDES FŐÉTELEK ── */
 { cat: 'Édes főétel', name: 'Túrós csusza', carbs: 50, unit: '1 adag (300 g)' },
 { cat: 'Édes főétel', name: 'Mákos tészta', carbs: 60, unit: '1 adag (300 g)' },
 { cat: 'Édes főétel', name: 'Grízes tészta', carbs: 62, unit: '1 adag (300 g)' },
 { cat: 'Édes főétel', name: 'Palacsinta (töltve)', carbs: 22, unit: '1 db' },
 { cat: 'Édes főétel', name: 'Túrógombóc', carbs: 18, unit: '1 db (80 g)' },
 { cat: 'Édes főétel', name: 'Szilvás gombóc', carbs: 25, unit: '1 db (90 g)' },
 { cat: 'Édes főétel', name: 'Bukta (lekváros)', carbs: 32, unit: '1 db (75 g)' },
 { cat: 'Édes főétel', name: 'Aranygaluska', carbs: 45, unit: '1 adag (150 g)' },
 { cat: 'Édes főétel', name: 'Rizsfelfújt', carbs: 40, unit: '1 adag (200 g)' },
 { cat: 'Édes főétel', name: 'Tejbegríz', carbs: 35, unit: '1 adag (250 g)' },
 { cat: 'Édes főétel', name: 'Tejberizs', carbs: 40, unit: '1 adag (250 g)' },

 /* ── GYÜMÖLCSÖK ── */
 { cat: 'Gyümölcs', name: 'Alma', carbs: 15, unit: '1 közepes db (130 g)' },
 { cat: 'Gyümölcs', name: 'Körte', carbs: 18, unit: '1 közepes db (150 g)' },
 { cat: 'Gyümölcs', name: 'Banán', carbs: 25, unit: '1 közepes db (120 g)' },
 { cat: 'Gyümölcs', name: 'Narancs', carbs: 15, unit: '1 közepes db (150 g)' },
 { cat: 'Gyümölcs', name: 'Mandarin', carbs: 6, unit: '1 db (60 g)' },
 { cat: 'Gyümölcs', name: 'Grapefruit', carbs: 12, unit: '1/2 db (150 g)' },
 { cat: 'Gyümölcs', name: 'Őszibarack', carbs: 12, unit: '1 közepes db (130 g)' },
 { cat: 'Gyümölcs', name: 'Sárgabarack', carbs: 5, unit: '1 db (50 g)' },
 { cat: 'Gyümölcs', name: 'Nektarin', carbs: 13, unit: '1 közepes db (130 g)' },
 { cat: 'Gyümölcs', name: 'Szilva', carbs: 5, unit: '1 db (50 g)' },
 { cat: 'Gyümölcs', name: 'Cseresznye', carbs: 15, unit: '1 marék (100 g)' },
 { cat: 'Gyümölcs', name: 'Meggy', carbs: 12, unit: '1 marék (100 g)' },
 { cat: 'Gyümölcs', name: 'Szőlő', carbs: 17, unit: '1 kis fürt (100 g)' },
 { cat: 'Gyümölcs', name: 'Eper', carbs: 8, unit: '1 tálka (150 g)' },
 { cat: 'Gyümölcs', name: 'Málna', carbs: 6, unit: '1 tálka (125 g)' },
 { cat: 'Gyümölcs', name: 'Áfonya', carbs: 12, unit: '1 tálka (125 g)' },
 { cat: 'Gyümölcs', name: 'Görögdinnye', carbs: 16, unit: '1 nagy szelet (250 g)' },
 { cat: 'Gyümölcs', name: 'Sárgadinnye', carbs: 14, unit: '1 nagy szelet (200 g)' },
 { cat: 'Gyümölcs', name: 'Kivi', carbs: 8, unit: '1 db (75 g)' },
 { cat: 'Gyümölcs', name: 'Ananász (friss)', carbs: 13, unit: '1 szelet (100 g)' },
 { cat: 'Gyümölcs', name: 'Mangó', carbs: 25, unit: '1/2 db (150 g)' },
 { cat: 'Gyümölcs', name: 'Datolya (aszalt)', carbs: 15, unit: '2 db (20 g)' },
 { cat: 'Gyümölcs', name: 'Aszalt szilva', carbs: 12, unit: '3 db (25 g)' },
 { cat: 'Gyümölcs', name: 'Mazsola', carbs: 15, unit: '2 evőkanál (20 g)' },

 /* ── ZÖLDSÉGEK ── */
 { cat: 'Zöldség', name: 'Paradicsom', carbs: 4, unit: '1 közepes db (120 g)' },
 { cat: 'Zöldség', name: 'TV paprika', carbs: 3, unit: '1 db (80 g)' },
 { cat: 'Zöldség', name: 'Kígyóuborka', carbs: 2, unit: '10 cm-es darab (100 g)' },
 { cat: 'Zöldség', name: 'Sárgarépa', carbs: 7, unit: '1 közepes db (100 g)' },
 { cat: 'Zöldség', name: 'Retek', carbs: 1, unit: '5 db (50 g)' },
 { cat: 'Zöldség', name: 'Saláta (fejes)', carbs: 2, unit: '1 tál (100 g)' },
 { cat: 'Zöldség', name: 'Káposzta (nyers)', carbs: 5, unit: '1 adag (100 g)' },
 { cat: 'Zöldség', name: 'Savanyú káposzta', carbs: 4, unit: '1 adag (100 g)' },
 { cat: 'Zöldség', name: 'Cékla (főtt)', carbs: 8, unit: '1 adag (80 g)' },
 { cat: 'Zöldség', name: 'Brokkoli (párolt)', carbs: 4, unit: '1 adag (100 g)' },
 { cat: 'Zöldség', name: 'Karfiol (párolt)', carbs: 4, unit: '1 adag (100 g)' },
 { cat: 'Zöldség', name: 'Cukkini', carbs: 3, unit: '1 adag (100 g)' },
 { cat: 'Zöldség', name: 'Padlizsán', carbs: 4, unit: '1 adag (100 g)' },
 { cat: 'Zöldség', name: 'Zöldborsó (főtt)', carbs: 12, unit: '1 adag (100 g)' },
 { cat: 'Zöldség', name: 'Zöldbab (párolt)', carbs: 7, unit: '1 adag (100 g)' },
 { cat: 'Zöldség', name: 'Gomba (natúr)', carbs: 1, unit: '1 adag (100 g)' },
 { cat: 'Zöldség', name: 'Hagyma', carbs: 5, unit: '1 közepes db (60 g)' },
 { cat: 'Zöldség', name: 'Avokádó', carbs: 2, unit: '1/2 db (70 g)' },

 /* ── TEJTERMÉKEK ── */
 { cat: 'Tejtermék', name: 'Tej (2,8%)', carbs: 10, unit: '2 dl' },
 { cat: 'Tejtermék', name: 'Tej (1,5%)', carbs: 10, unit: '2 dl' },
 { cat: 'Tejtermék', name: 'Kakaó (cukrozott)', carbs: 25, unit: '2 dl' },
 { cat: 'Tejtermék', name: 'Kefir', carbs: 8, unit: '1 pohár (175 g)' },
 { cat: 'Tejtermék', name: 'Natúr joghurt', carbs: 7, unit: '1 pohár (150 g)' },
 { cat: 'Tejtermék', name: 'Gyümölcsjoghurt', carbs: 20, unit: '1 pohár (150 g)' },
 { cat: 'Tejtermék', name: 'Görög joghurt (natúr)', carbs: 6, unit: '1 pohár (150 g)' },
 { cat: 'Tejtermék', name: 'Túró (félzsíros)', carbs: 3, unit: '1 adag (100 g)' },
 { cat: 'Tejtermék', name: 'Túró Rudi', carbs: 15, unit: '1 db (30 g)' },
 { cat: 'Tejtermék', name: 'Sajt (trappista)', carbs: 0, unit: '2 szelet (40 g)' },
 { cat: 'Tejtermék', name: 'Ömlesztett sajt', carbs: 2, unit: '2 kocka (35 g)' },
 { cat: 'Tejtermék', name: 'Tejföl (20%)', carbs: 2, unit: '2 evőkanál (50 g)' },
 { cat: 'Tejtermék', name: 'Vaj', carbs: 0, unit: '1 evőkanál (20 g)' },
 { cat: 'Tejtermék', name: 'Tejszínhab (cukrozott)', carbs: 6, unit: '1 adag (30 g)' },
 { cat: 'Tejtermék', name: 'Puding (bolti)', carbs: 22, unit: '1 pohár (125 g)' },

 /* ── ÉDESSÉGEK, NASSOLNIVALÓK ── */
 { cat: 'Édesség', name: 'Tejcsokoládé', carbs: 12, unit: '4 kocka (20 g)' },
 { cat: 'Édesség', name: 'Étcsokoládé (70%)', carbs: 7, unit: '4 kocka (20 g)' },
 { cat: 'Édesség', name: 'Szőlőcukor', carbs: 3, unit: '1 tabletta' },
 { cat: 'Édesség', name: 'Méz', carbs: 17, unit: '1 evőkanál (20 g)' },
 { cat: 'Édesség', name: 'Kristálycukor', carbs: 4, unit: '1 teáskanál' },
 { cat: 'Édesség', name: 'Lekvár', carbs: 12, unit: '1 evőkanál (20 g)' },
 { cat: 'Édesség', name: 'Nutella', carbs: 11, unit: '1 evőkanál (20 g)' },
 { cat: 'Édesség', name: 'Háztartási keksz', carbs: 7, unit: '1 db (9 g)' },
 { cat: 'Édesség', name: 'Vajas keksz', carbs: 6, unit: '1 db (8 g)' },
 { cat: 'Édesség', name: 'Nápolyi', carbs: 9, unit: '1 db (15 g)' },
 { cat: 'Édesség', name: 'Piskóta', carbs: 15, unit: '1 szelet (30 g)' },
 { cat: 'Édesség', name: 'Kevert sütemény', carbs: 30, unit: '1 szelet (70 g)' },
 { cat: 'Édesség', name: 'Dobostorta', carbs: 35, unit: '1 szelet (100 g)' },
 { cat: 'Édesség', name: 'Somlói galuska', carbs: 45, unit: '1 adag (180 g)' },
 { cat: 'Édesség', name: 'Rétes (almás)', carbs: 35, unit: '1 db (100 g)' },
 { cat: 'Édesség', name: 'Fagylalt', carbs: 15, unit: '1 gombóc (50 g)' },
 { cat: 'Édesség', name: 'Jégkrém (pálcikás)', carbs: 20, unit: '1 db' },
 { cat: 'Édesség', name: 'Gumicukor', carbs: 16, unit: '1 marék (20 g)' },
 { cat: 'Édesség', name: 'Müzliszelet', carbs: 18, unit: '1 db (25 g)' },
 { cat: 'Édesség', name: 'Raffaello', carbs: 5, unit: '1 db' },
 { cat: 'Édesség', name: 'Chips (burgonya)', carbs: 15, unit: '1 kis zacskó fele (30 g)' },
 { cat: 'Édesség', name: 'Sósperec / ropi', carbs: 16, unit: '1 marék (20 g)' },
 { cat: 'Édesség', name: 'Popcorn (sós)', carbs: 12, unit: '1 tálka (20 g)' },
 { cat: 'Édesség', name: 'Dió / mogyoró (natúr)', carbs: 3, unit: '1 marék (30 g)' },
 { cat: 'Édesség', name: 'Mandula (natúr)', carbs: 2, unit: '1 marék (30 g)' },

 /* ── ITALOK ── */
 { cat: 'Ital', name: 'Narancslé (100%)', carbs: 20, unit: '2 dl' },
 { cat: 'Ital', name: 'Almalé (100%)', carbs: 22, unit: '2 dl' },
 { cat: 'Ital', name: 'Paradicsomlé', carbs: 8, unit: '2 dl' },
 { cat: 'Ital', name: 'Kóla', carbs: 21, unit: '2 dl' },
 { cat: 'Ital', name: 'Kóla (zero/light)', carbs: 0, unit: '2 dl' },
 { cat: 'Ital', name: 'Fanta / narancsos üdítő', carbs: 22, unit: '2 dl' },
 { cat: 'Ital', name: 'Szörp (hígítva)', carbs: 18, unit: '2 dl' },
 { cat: 'Ital', name: 'Ice tea (cukrozott)', carbs: 14, unit: '2 dl' },
 { cat: 'Ital', name: 'Ásványvíz', carbs: 0, unit: 'bármennyi' },
 { cat: 'Ital', name: 'Kávé (cukor nélkül)', carbs: 0, unit: '1 csésze' },
 { cat: 'Ital', name: 'Cappuccino (cukrozott)', carbs: 12, unit: '1 csésze (2 dl)' },
 { cat: 'Ital', name: 'Tejeskávé (cukor nélkül)', carbs: 6, unit: '1 csésze (2 dl)' },
 { cat: 'Ital', name: 'Sör (világos)', carbs: 15, unit: '0,5 l' },
 { cat: 'Ital', name: 'Vörösbor (száraz)', carbs: 3, unit: '1,5 dl' },
 { cat: 'Ital', name: 'Fehérbor (száraz)', carbs: 3, unit: '1,5 dl' },
 { cat: 'Ital', name: 'Pezsgő (száraz)', carbs: 2, unit: '1 dl' },
 { cat: 'Ital', name: 'Smoothie (gyümölcs)', carbs: 30, unit: '2,5 dl' },
 { cat: 'Ital', name: 'Energiaital', carbs: 27, unit: '2,5 dl' },

 /* ── GYORS HIPÓ-KEZELÉS (15 g szabály) ── */
 { cat: 'Hipó-kezelés', name: 'Szőlőcukor 5 tabletta (hipóra)', carbs: 15, unit: '5 tabletta' },
 { cat: 'Hipó-kezelés', name: 'Gyümölcslé 1,5 dl (hipóra)', carbs: 15, unit: '1,5 dl' },
 { cat: 'Hipó-kezelés', name: 'Cukros üdítő 1,5 dl (hipóra)', carbs: 15, unit: '1,5 dl' },
 { cat: 'Hipó-kezelés', name: 'Méz 1 evőkanál (hipóra)', carbs: 15, unit: '~1 evőkanál' }
];
